// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeNV0I7aCIzrAxiIvysVZ35Xt859Kj9bs',
    appId: '1:304575478519:web:18019fee69bab3bd2cf1f2',
    messagingSenderId: '304575478519',
    projectId: 'foodregime-c72a3',
    authDomain: 'foodregime-c72a3.firebaseapp.com',
    storageBucket: 'foodregime-c72a3.firebasestorage.app',
    measurementId: 'G-2MJTW6MWG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3t18z0CwwjW-nDIsP0y2fU5QOoDW7ISs',
    appId: '1:304575478519:android:344b89f8ee4b19672cf1f2',
    messagingSenderId: '304575478519',
    projectId: 'foodregime-c72a3',
    storageBucket: 'foodregime-c72a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAknAiiSSV2mMee5aZeHXdnPYPi0QpwnL8',
    appId: '1:304575478519:ios:e5db458c1f669f222cf1f2',
    messagingSenderId: '304575478519',
    projectId: 'foodregime-c72a3',
    storageBucket: 'foodregime-c72a3.firebasestorage.app',
    iosBundleId: 'com.app.foodregime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAknAiiSSV2mMee5aZeHXdnPYPi0QpwnL8',
    appId: '1:304575478519:ios:e5db458c1f669f222cf1f2',
    messagingSenderId: '304575478519',
    projectId: 'foodregime-c72a3',
    storageBucket: 'foodregime-c72a3.firebasestorage.app',
    iosBundleId: 'com.app.foodregime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeNV0I7aCIzrAxiIvysVZ35Xt859Kj9bs',
    appId: '1:304575478519:web:55ba0fec599a4b3f2cf1f2',
    messagingSenderId: '304575478519',
    projectId: 'foodregime-c72a3',
    authDomain: 'foodregime-c72a3.firebaseapp.com',
    storageBucket: 'foodregime-c72a3.firebasestorage.app',
    measurementId: 'G-44ZB4VHNY4',
  );
}
